apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-app
  labels:
    app: abc-tech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-tech-app
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
      - name: abc-tech-app
        image: iambowcreek/abc_technologies:latest
        ports:
        - containerPort: 80